apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
stringData:
  DB_POSTGRESDB_PASSWORD: "n8n"
  N8N_ENCRYPTION_KEY: "n8n"
  N8N_BASIC_AUTH_PASSWORD: "n8n"
  N8N_BASIC_AUTH_USER: "n8n"
